version: '3.1'

services:
    service-proxy:
        image: nginx:latest
        container_name: service-proxy
        depends_on:
            - service-localisation
            - service-web
            - service-java
        volumes:
            - ./service-proxy/nginx.conf:/etc/nginx/nginx.conf
            - ./service-proxy/:/www/data
        ports:
            - 80:80

    service-web:
        image: service-web
        container_name: service-web
        build:
            context: ./service-web
        ports:
            - 5010:80
            - 5011:443
        volumes:
            - ./service-web/html:/var/www/html/

    service-localisation:
        image: service-localisation
        container_name: service-localisation
        build:
            context: ./service-localisation
        ports:
            - 5000:5000
        restart: on-failure

    service-java:
        image: service-java
        container_name: service-java
        build:
            context: ./service-java
        ports:
            - 5020:4444
            - 5021:443
 
    service-db:
        image: mariadb:latest
        container_name: service-db
        environment:
            MYSQL_ROOT_PASSWORD: changeme
            MYSQL_DATABASE: mybb
            MYSQL_USER: mybb
            MYSQL_PASSWORD: changeme
        ports:
            - 3306:3306
        restart: on-failure
        volumes:
            - ./service-db/database:/var/lib/mysql
            - ./service-db/conf:/etc/mysql