version: '3.1'

services:
    service-proxy:
        image: nginx:latest
        container_name: service-proxy
        depends_on:
            - service-localisation
            - service-java
        links: 
            - "service-java:serveurSGBD"
            - "service-localisation:serveurModele"
        volumes:
            - ./service-proxy/nginx.conf:/etc/nginx/nginx.conf
            - ./service-proxy/:/www/data
            - ./service-proxy/certificat:/etc/certificat
        ports:
            - 17080:80
            - 17443:443
        restart: on-failure

    service-localisation:
        image: service-localisation
        container_name: service-localisation
        depends_on:
            - service-java
        links: 
            - "service-java:serveurSGBD"
        build:
            context: ../../
            dockerfile: ./Cloud/Docker/service-localisation/Dockerfile
        restart: on-failure

    service-java:
        image: service-java
        container_name: service-java
        depends_on:
            - service-db
        links: 
            - "service-db:database"
        build:
            context: ../../
            dockerfile: ./Cloud/Docker/service-java/Dockerfile
 
    service-db:
        image: mariadb:10.4
        container_name: service-db
        environment:
            MYSQL_ROOT_PASSWORD: changeme
            MYSQL_DATABASE: mybb
            MYSQL_USER: mybb
            MYSQL_PASSWORD: changeme
        ports:
            - 3306:3306
        restart: on-failure
        volumes:
            - ./service-db/database:/var/lib/mysql
            - ./service-db/conf:/etc/mysql
            
            

